-- =====================================================
-- Project #2 (V2) - Analytics DB initialization
-- PostgreSQL 16
--
-- Назначение:
-- - создать analytics schema
-- - создать event-store таблицу inventory_status_events
-- - создать snapshot таблицу current_batch_state
-- - создать worker_state и инициализировать watermark
--
-- Важно:
-- PostgreSQL 16 не позволяет создать PRIMARY KEY или UNIQUE
-- constraint/index на partitioned table, если в ключ не входит
-- partition key. Поэтому для валидного DDL:
-- - PRIMARY KEY создан как (event_time, event_id)
-- - UNIQUE index создан как (operation_id, event_time)
--
-- Это минимально необходимая техническая адаптация под RANGE
-- partitioning по event_time без изменения имен таблиц и полей.
-- =====================================================

-- -----------------------------------------------------
-- 1) Schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS analytics;

-- -----------------------------------------------------
-- 2) Event store
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.inventory_status_events (
    event_id BIGSERIAL NOT NULL,
    batch_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    source_location_id BIGINT,
    destination_location_id BIGINT,
    status_id INT NOT NULL,
    status_reason_id INT NOT NULL,
    quantity BIGINT NOT NULL CHECK (quantity > 0),
    event_time TIMESTAMPTZ NOT NULL,
    ingest_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_system INT NOT NULL,
    operation_id BIGINT NOT NULL,
    PRIMARY KEY (event_time, event_id)
) PARTITION BY RANGE (event_time);

COMMENT ON TABLE analytics.inventory_status_events IS
    'Append-only event store for batch inventory history.';

COMMENT ON COLUMN analytics.inventory_status_events.event_id IS
    'Monotonic event identifier generated by BIGSERIAL.';

COMMENT ON COLUMN analytics.inventory_status_events.operation_id IS
    'Business operation identifier used for idempotent worker writes.';

-- -----------------------------------------------------
-- 3) Example partition
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.inventory_status_events_2026_01
    PARTITION OF analytics.inventory_status_events
    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');

COMMENT ON TABLE analytics.inventory_status_events_2026_01 IS
    'Monthly partition for January 2026.';

-- -----------------------------------------------------
-- 4) Indexes
-- -----------------------------------------------------
-- PostgreSQL 16 limitation:
-- unique index on a partitioned parent must include event_time.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_operation_id
    ON analytics.inventory_status_events (operation_id, event_time);

CREATE INDEX IF NOT EXISTS idx_events_batch_time
    ON analytics.inventory_status_events (batch_id, event_time DESC);

-- -----------------------------------------------------
-- 5) Snapshot table
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.current_batch_state (
    batch_id BIGINT PRIMARY KEY,
    order_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    status_id INT NOT NULL,
    quantity BIGINT NOT NULL,
    source_location_id BIGINT,
    destination_location_id BIGINT,
    last_event_time TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE analytics.current_batch_state IS
    'Operational snapshot of active batches only.';

CREATE INDEX IF NOT EXISTS idx_current_batch_wh_status
    ON analytics.current_batch_state (warehouse_id, status_id);

-- -----------------------------------------------------
-- 6) Worker state
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.worker_state (
    worker_name TEXT PRIMARY KEY,
    last_processed_event_id BIGINT NOT NULL
);

COMMENT ON TABLE analytics.worker_state IS
    'Stores worker watermark for sequential event processing.';

-- -----------------------------------------------------
-- 7) Worker state initialization
-- -----------------------------------------------------
INSERT INTO analytics.worker_state (worker_name, last_processed_event_id)
VALUES ('analytics_worker', 0)
ON CONFLICT (worker_name) DO NOTHING;
