-- =====================================================
-- Project #2 (V2) - Analytics DB initialization
-- PostgreSQL 16
--
-- Назначение:
-- - создать analytics schema
-- - создать event-store таблицу inventory_status_events
-- - создать snapshot таблицу current_batch_state
-- - создать worker_state и инициализировать watermark
--
-- Важно:
-- PostgreSQL 16 не позволяет создать PRIMARY KEY или UNIQUE
-- constraint/index на partitioned table, если в ключ не входит
-- partition key. Поэтому для валидного DDL:
-- - PRIMARY KEY создан как (event_time, event_id)
-- - UNIQUE index создан как (operation_id, event_time)
--
-- Это минимально необходимая техническая адаптация под RANGE
-- partitioning по event_time без изменения имен таблиц и полей.
-- =====================================================

-- -----------------------------------------------------
-- 1) Schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS analytics;

-- -----------------------------------------------------
-- 2) Event store
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.inventory_status_events (
    event_id BIGSERIAL NOT NULL,
    batch_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    source_location_id BIGINT,
    destination_location_id BIGINT,
    status_id INT NOT NULL,
    status_reason_id INT NOT NULL,
    quantity BIGINT NOT NULL CHECK (quantity > 0),
    event_time TIMESTAMPTZ NOT NULL,
    ingest_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_system INT NOT NULL,
    operation_id BIGINT NOT NULL,
    PRIMARY KEY (event_time, event_id)
) PARTITION BY RANGE (event_time);

COMMENT ON TABLE analytics.inventory_status_events IS
    'Append-only event store for batch inventory history.';

COMMENT ON COLUMN analytics.inventory_status_events.event_id IS
    'Monotonic event identifier generated by BIGSERIAL.';

COMMENT ON COLUMN analytics.inventory_status_events.operation_id IS
    'Business operation identifier used for idempotent worker writes.';

-- -----------------------------------------------------
-- 2.1) Partition management helper
-- -----------------------------------------------------
CREATE OR REPLACE FUNCTION analytics.create_month_partition(
    target_timestamp TIMESTAMPTZ
)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    partition_start TIMESTAMPTZ := date_trunc('month', target_timestamp);
    partition_end TIMESTAMPTZ := partition_start + INTERVAL '1 month';
    partition_name TEXT := format(
        'inventory_status_events_%s',
        to_char(partition_start, 'YYYY_MM')
    );
    qualified_name TEXT := format('analytics.%I', partition_name);
    partition_exists BOOLEAN := to_regclass(qualified_name) IS NOT NULL;
BEGIN
    IF NOT partition_exists THEN
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS analytics.%I PARTITION OF analytics.inventory_status_events FOR VALUES FROM (%L) TO (%L)',
            partition_name,
            partition_start,
            partition_end
        );

        RETURN partition_name;
    END IF;

    RETURN NULL;
END;
$$;

COMMENT ON FUNCTION analytics.create_month_partition(TIMESTAMPTZ) IS
    'Creates monthly partition for analytics.inventory_status_events if missing. Returns partition name only when newly created.';

-- -----------------------------------------------------
-- 3) Example partition
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.inventory_status_events_2026_01
    PARTITION OF analytics.inventory_status_events
    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');

COMMENT ON TABLE analytics.inventory_status_events_2026_01 IS
    'Monthly partition for January 2026.';

-- -----------------------------------------------------
-- 4) Indexes
-- -----------------------------------------------------
-- PostgreSQL 16 limitation:
-- unique index on a partitioned parent must include event_time.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_operation_id
    ON analytics.inventory_status_events (operation_id, event_time);

CREATE INDEX IF NOT EXISTS idx_events_batch_time
    ON analytics.inventory_status_events (batch_id, event_time DESC);

-- -----------------------------------------------------
-- 5) Snapshot table
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.current_batch_state (
    batch_id BIGINT PRIMARY KEY,
    order_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    status_id INT NOT NULL,
    quantity BIGINT NOT NULL,
    source_location_id BIGINT,
    destination_location_id BIGINT,
    last_event_time TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE analytics.current_batch_state IS
    'Operational snapshot of active batches only.';

CREATE INDEX IF NOT EXISTS idx_current_batch_wh_status
    ON analytics.current_batch_state (warehouse_id, status_id);

-- -----------------------------------------------------
-- 6) Reference data: status dictionaries
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.status_dict (
    status_id INT PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    description TEXT NOT NULL
);

COMMENT ON TABLE analytics.status_dict IS
    'Reference data: canonical status dictionary for analytics events.';

COMMENT ON COLUMN analytics.status_dict.code IS
    'Stable status code used by ingest/events integration.';

CREATE TABLE IF NOT EXISTS analytics.status_reason (
    status_reason_id INT PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    description TEXT NOT NULL,
    is_tracking_finished BOOLEAN NOT NULL
);

COMMENT ON TABLE analytics.status_reason IS
    'Reference data: status reasons with tracking-finality flag.';

COMMENT ON COLUMN analytics.status_reason.is_tracking_finished IS
    'TRUE means batch tracking is finished and must be removed from snapshot.';

-- -----------------------------------------------------
-- 7) Worker state
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.worker_state (
    worker_name TEXT PRIMARY KEY,
    last_processed_event_id BIGINT NOT NULL
);

COMMENT ON TABLE analytics.worker_state IS
    'Stores worker watermark for sequential event processing.';

-- -----------------------------------------------------
-- 8) Worker state initialization
-- -----------------------------------------------------
INSERT INTO analytics.worker_state (worker_name, last_processed_event_id)
VALUES ('analytics_worker', 0)
ON CONFLICT (worker_name) DO NOTHING;

INSERT INTO analytics.status_dict (status_id, code, description)
VALUES

   (-1, 'DELETED', 'Удалено'), 
   (1, 'RECEIPT', 'Принято'),
   (2, 'PACKAGED', 'Упаковано'),
   (3, 'SHIPPED', 'Отгружено'),
   (4, 'RETURNED', 'Возвращено'),
   (5, 'DELIVERED', 'Доставлено'),
   (6, 'IN_TRANSIT', 'В пути')
ON CONFLICT (status_id) DO NOTHING;

INSERT INTO analytics.status_reason (
    status_reason_id,
    code,
    description,
    is_tracking_finished
)
VALUES
    (-1, 'DELETED', 'Удалено', true),
    (0, 'UNKNOWN', 'Неизвестно', false),
    (1, 'RECEIPT_FIRST', 'Принято первично', false),
    (2, 'RECEIPT_SECOND', 'Принято вторично', false),
    (3, 'RECEIPT_NOTHING', 'Принято неизвестно', false),
    (4, 'PACKAGE_TERMINAL', 'Упаковано терминалом', false),
    (5, 'PACKAGE_OLD_APP', 'Упаковано в старом приложении', false),
    (6, 'PACKAGE_NEW_APP', 'Упаковано в новом приложении', false),
    (7, 'PACKAGE_NOTHING', 'Упаковано неизвестно', false),
    (8, 'SHIPPED_CLIENT', 'Отгружено клиенту', false),
    (9, 'SHIPPED_WAREHOUSE', 'Отгружено на склад', false),
    (10, 'SHIPPED_EXPEDITION', 'Отгружено экспедитору', false),
    (11, 'DELIVERED_CLIENT', 'Доставлено клиенту', true),
    (12, 'DELIVERED_WAREHOUSE', 'Доставлено на склад', false),
    (13, 'DELIVERED_EXPEDITION', 'Доставлено экспедитору', false),
    (14, 'RETURNED_WAREHOUSE', 'Возвращено на склад', false),
    (15, 'IN_TRANSIT_CLIENT', 'В пути клиенту', false),
    (16, 'IN_TRANSIT_WAREHOUSE', 'В пути на склад', false),
    (17, 'IN_TRANSIT_EXPEDITION', 'В пути экспедитору', false),
    (18, 'MOVED', 'Перемещение', false)
ON CONFLICT (status_reason_id) DO NOTHING;

-- -----------------------------------------------------
-- 9) Project #3 reference layer: cities + warehouses
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.cities (
    city_id BIGINT PRIMARY KEY,
    name TEXT NOT NULL
);

COMMENT ON TABLE analytics.cities IS
    'Reference data: city dictionary for analytics warehouse master table.';

COMMENT ON COLUMN analytics.cities.city_id IS
    'Stable city identifier used by analytics.warehouses.';

-- Защита от дублей названий города без учёта регистра.
CREATE UNIQUE INDEX IF NOT EXISTS idx_cities_name_unique
    ON analytics.cities (lower(name));

CREATE TABLE IF NOT EXISTS analytics.warehouse_types (
    warehouse_type_id INT PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);

COMMENT ON TABLE analytics.warehouse_types IS
    'Reference data: dictionary of warehouse types for Project #3 analytics warehouse master data.';

COMMENT ON COLUMN analytics.warehouse_types.warehouse_type_id IS
    'Stable identifier of warehouse type used in analytics.warehouses.';

COMMENT ON COLUMN analytics.warehouse_types.code IS
    'Machine-readable unique type code for integrations and business logic.';

COMMENT ON COLUMN analytics.warehouse_types.name IS
    'Human-readable warehouse type name for UI and reports.';

INSERT INTO analytics.warehouse_types (warehouse_type_id, code, name) VALUES
    (1, 'LOGISTICS_CENTER', 'Логистический центр'),
    (2, 'EXPEDITOR', 'Экспедитор'),
    (3, 'STORAGE', 'Склад хранения'),
    (4, 'TRANSIT', 'Транзитный склад')
ON CONFLICT (warehouse_type_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS analytics.warehouses (
    warehouse_id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    city_id BIGINT NOT NULL,
    warehouse_type_id INT NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE analytics.warehouses IS
    'Master table for warehouses in analytics; source for map in Project #3.';

COMMENT ON COLUMN analytics.warehouses.warehouse_id IS
    'Warehouse identifier aligned 1:1 with OLTP warehouse id.';

COMMENT ON COLUMN analytics.warehouses.city_id IS
    'City identifier from analytics.cities reference data.';

COMMENT ON COLUMN analytics.warehouses.warehouse_type_id IS
    'Reference to warehouse type dictionary (external or future analytics table).';

COMMENT ON COLUMN analytics.warehouses.lat IS
    'Latitude in WGS84 stored as plain numeric value (no PostGIS in analytics).';

COMMENT ON COLUMN analytics.warehouses.lon IS
    'Longitude in WGS84 stored as plain numeric value (no PostGIS in analytics).';

CREATE INDEX IF NOT EXISTS idx_warehouses_city
    ON analytics.warehouses (city_id);

CREATE INDEX IF NOT EXISTS idx_warehouses_type
    ON analytics.warehouses (warehouse_type_id);

-- Диапазоны координат для защиты качества данных в master-таблице складов.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_lat_range'
          AND conrelid = 'analytics.warehouses'::regclass
    ) THEN
        ALTER TABLE analytics.warehouses
        ADD CONSTRAINT chk_lat_range
        CHECK (lat BETWEEN -90 AND 90);
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_lon_range'
          AND conrelid = 'analytics.warehouses'::regclass
    ) THEN
        ALTER TABLE analytics.warehouses
        ADD CONSTRAINT chk_lon_range
        CHECK (lon BETWEEN -180 AND 180);
    END IF;
END;
$$;

-- Автоматически обновляем updated_at при любом UPDATE строки склада.
CREATE OR REPLACE FUNCTION analytics.touch_warehouses_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_warehouses_updated_at
ON analytics.warehouses;

CREATE TRIGGER trg_touch_warehouses_updated_at
BEFORE UPDATE ON analytics.warehouses
FOR EACH ROW
EXECUTE FUNCTION analytics.touch_warehouses_updated_at();

CREATE TABLE IF NOT EXISTS analytics.ingest_dead_letter (
    id BIGSERIAL PRIMARY KEY,
    source_event_id BIGINT NOT NULL,
    payload JSONB NOT NULL,
    error TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);