-- =====================================================
-- Project #2 (V2) - Analytics DB initialization
-- PostgreSQL 16
--
-- Назначение:
-- - создать analytics schema
-- - создать event-store таблицу inventory_status_events
-- - создать snapshot таблицу current_batch_state
-- - создать worker_state и инициализировать watermark
--
-- Важно:
-- PostgreSQL 16 не позволяет создать PRIMARY KEY или UNIQUE
-- constraint/index на partitioned table, если в ключ не входит
-- partition key. Поэтому для валидного DDL:
-- - PRIMARY KEY создан как (event_time, event_id)
-- - UNIQUE index создан как (operation_id, event_time)
--
-- Это минимально необходимая техническая адаптация под RANGE
-- partitioning по event_time без изменения имен таблиц и полей.
-- =====================================================

-- -----------------------------------------------------
-- 1) Schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS analytics;

-- -----------------------------------------------------
-- 2) Event store
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.inventory_status_events (
    event_id BIGSERIAL NOT NULL,
    batch_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    source_location_id BIGINT,
    destination_location_id BIGINT,
    status_id INT NOT NULL,
    status_reason_id INT NOT NULL,
    quantity BIGINT NOT NULL CHECK (quantity > 0),
    event_time TIMESTAMPTZ NOT NULL,
    ingest_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_system INT NOT NULL,
    operation_id BIGINT NOT NULL,
    PRIMARY KEY (event_time, event_id)
) PARTITION BY RANGE (event_time);

COMMENT ON TABLE analytics.inventory_status_events IS
    'Append-only event store for batch inventory history.';

COMMENT ON COLUMN analytics.inventory_status_events.event_id IS
    'Monotonic event identifier generated by BIGSERIAL.';

COMMENT ON COLUMN analytics.inventory_status_events.operation_id IS
    'Business operation identifier used for idempotent worker writes.';

-- -----------------------------------------------------
-- 2.1) Partition management helper
-- -----------------------------------------------------
CREATE OR REPLACE FUNCTION analytics.create_month_partition(
    target_timestamp TIMESTAMPTZ
)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    partition_start TIMESTAMPTZ := date_trunc('month', target_timestamp);
    partition_end TIMESTAMPTZ := partition_start + INTERVAL '1 month';
    partition_name TEXT := format(
        'inventory_status_events_%s',
        to_char(partition_start, 'YYYY_MM')
    );
    qualified_name TEXT := format('analytics.%I', partition_name);
    partition_exists BOOLEAN := to_regclass(qualified_name) IS NOT NULL;
BEGIN
    IF NOT partition_exists THEN
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS analytics.%I PARTITION OF analytics.inventory_status_events FOR VALUES FROM (%L) TO (%L)',
            partition_name,
            partition_start,
            partition_end
        );

        RETURN partition_name;
    END IF;

    RETURN NULL;
END;
$$;

COMMENT ON FUNCTION analytics.create_month_partition(TIMESTAMPTZ) IS
    'Creates monthly partition for analytics.inventory_status_events if missing. Returns partition name only when newly created.';

-- -----------------------------------------------------
-- 3) Example partition
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.inventory_status_events_2026_01
    PARTITION OF analytics.inventory_status_events
    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');

COMMENT ON TABLE analytics.inventory_status_events_2026_01 IS
    'Monthly partition for January 2026.';

-- -----------------------------------------------------
-- 4) Indexes
-- -----------------------------------------------------
-- PostgreSQL 16 limitation:
-- unique index on a partitioned parent must include event_time.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_operation_id
    ON analytics.inventory_status_events (operation_id, event_time);

CREATE INDEX IF NOT EXISTS idx_events_batch_time
    ON analytics.inventory_status_events (batch_id, event_time DESC);

-- -----------------------------------------------------
-- 5) Snapshot table
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.current_batch_state (
    batch_id BIGINT PRIMARY KEY,
    order_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    status_id INT NOT NULL,
    quantity BIGINT NOT NULL,
    source_location_id BIGINT,
    destination_location_id BIGINT,
    last_event_time TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE analytics.current_batch_state IS
    'Operational snapshot of active batches only.';

CREATE INDEX IF NOT EXISTS idx_current_batch_wh_status
    ON analytics.current_batch_state (warehouse_id, status_id);

-- -----------------------------------------------------
-- 6) Reference data: status dictionaries
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.status_dict (
    status_id INT PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    description TEXT NOT NULL
);

COMMENT ON TABLE analytics.status_dict IS
    'Reference data: canonical status dictionary for analytics events.';

COMMENT ON COLUMN analytics.status_dict.code IS
    'Stable status code used by ingest/events integration.';

CREATE TABLE IF NOT EXISTS analytics.status_reason (
    status_reason_id INT PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    description TEXT NOT NULL,
    is_tracking_finished BOOLEAN NOT NULL
);

COMMENT ON TABLE analytics.status_reason IS
    'Reference data: status reasons with tracking-finality flag.';

COMMENT ON COLUMN analytics.status_reason.is_tracking_finished IS
    'TRUE means batch tracking is finished and must be removed from snapshot.';

-- -----------------------------------------------------
-- 7) Worker state
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics.worker_state (
    worker_name TEXT PRIMARY KEY,
    last_processed_event_id BIGINT NOT NULL
);

COMMENT ON TABLE analytics.worker_state IS
    'Stores worker watermark for sequential event processing.';

-- -----------------------------------------------------
-- 8) Worker state initialization
-- -----------------------------------------------------
INSERT INTO analytics.worker_state (worker_name, last_processed_event_id)
VALUES ('analytics_worker', 0)
ON CONFLICT (worker_name) DO NOTHING;

INSERT INTO analytics.status_dict (status_id, code, description)
VALUES

   (-1, 'DELETED', 'Удалено'), 
   (1, 'RECEIPT', 'Принято'),
   (2, 'PACKAGED', 'Упаковано'),
   (3, 'SHIPPED', 'Отгружено'),
   (4, 'RETURNED', 'Возвращено'),
   (5, 'DELIVERED', 'Доставлено'),
   (6, 'IN_TRANSIT', 'В пути')
ON CONFLICT (status_id) DO NOTHING;

INSERT INTO analytics.status_reason (
    status_reason_id,
    code,
    description,
    is_tracking_finished
)
VALUES
    (-1, 'DELETED', 'Удалено', true),
    (0, 'UNKNOWN', 'Неизвестно', false),
    (1, 'RECEIPT_FIRST', 'Принято первично', false),
    (2, 'RECEIPT_SECOND', 'Принято вторично', false),
    (3, 'RECEIPT_NOTHING', 'Принято неизвестно', false),
    (4, 'PACKAGE_TERMINAL', 'Упаковано терминалом', false),
    (5, 'PACKAGE_OLD_APP', 'Упаковано в старом приложении', false),
    (6, 'PACKAGE_NEW_APP', 'Упаковано в новом приложении', false),
    (7, 'PACKAGE_NOTHING', 'Упаковано неизвестно', false),
    (8, 'SHIPPED_CLIENT', 'Отгружено клиенту', false),
    (9, 'SHIPPED_WAREHOUSE', 'Отгружено на склад', false),
    (10, 'SHIPPED_EXPEDITION', 'Отгружено экспедитору', false),
    (11, 'DELIVERED_CLIENT', 'Доставлено клиенту', true),
    (12, 'DELIVERED_WAREHOUSE', 'Доставлено на склад', false),
    (13, 'DELIVERED_EXPEDITION', 'Доставлено экспедитору', false),
    (14, 'RETURNED_WAREHOUSE', 'Возвращено на склад', false),
    (15, 'IN_TRANSIT_CLIENT', 'В пути клиенту', false),
    (16, 'IN_TRANSIT_WAREHOUSE', 'В пути на склад', false),
    (17, 'IN_TRANSIT_EXPEDITION', 'В пути экспедитору', false),
    (18, 'MOVED', 'Перемещение', false)
ON CONFLICT (status_reason_id) DO NOTHING;